module.exports = {
    formateError: null,
    defaultMsg: {
        required: 'missing filed',
        isReg: 'not match',
        notReg: 'match',
        isEmail: 'not email',
        isUrl: 'not url',
        isIP: 'not IP',
        isAlpha: 'not all letter',
        isAlphanumeric: ' not letter or number',
        isNumeric: 'not a number',
        isInt: 'not int number',
        isFloat: 'not float number',
        isLowercase: 'letters are not small letter',
        isUppercase: 'letters are not big letter',
        notNull: 'not allow null',
        isNull: 'must be null',
        notEmpty: 'string not allow empty',
        contains: 'not contain require letters',
        notIn: 'is in required array',
        isIn: 'not in required array',
        len: 'the length is out of bounds',
        max: 'the number bigger than max value',
        min: 'the number samller than min value',        
    }   
}